# Example of tensors representing qubits



<img src="../logo_circular.png" width="20" height="20" />@by claudio<br>
nonlinearxwaves@gmail.com<br>


@created 27 February 2022<br>
@version 6 October 2023<br> 

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # disable warning messages 

In [2]:
from thqml.quantummap import *
import tensorflow as  tf
import matplotlib.pyplot as plt
from matplotlib import cm

# Single qubit examples

In [3]:
psi = 3.0*qubit0+2j*qubit1
print(psi)

tf.Tensor([3.+0.j 0.+2.j], shape=(2,), dtype=complex64)


In [4]:
phi = 3j*qubit0+1.5*qubit1
print(phi)

tf.Tensor([0. +3.j 1.5+0.j], shape=(2,), dtype=complex64)


# Build the two qubit example as an outer product

In [5]:
Psi=tf.tensordot(psi,phi,axes=0)
print(Psi)

tf.Tensor(
[[ 0. +9.j  4.5+0.j]
 [-6. +0.j  0. +3.j]], shape=(2, 2), dtype=complex64)


In [6]:
print(psi)

tf.Tensor([3.+0.j 0.+2.j], shape=(2,), dtype=complex64)


In [7]:
Psi[0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0. +9.j, 4.5+0.j], dtype=complex64)>

In [8]:
Psi[1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-6.+0.j,  0.+3.j], dtype=complex64)>

## Print the components

In [9]:
print(Psi[0,0])

tf.Tensor(9j, shape=(), dtype=complex64)


In [10]:
print(Psi[0,1])

tf.Tensor((4.5+0j), shape=(), dtype=complex64)


In [11]:
print(Psi[1,0])

tf.Tensor((-6+0j), shape=(), dtype=complex64)


In [12]:
print(Psi[1,1])

tf.Tensor(3j, shape=(), dtype=complex64)


#  Two-qubit gate

In [13]:
HH

<tf.Tensor: shape=(2, 2, 2, 2), dtype=complex64, numpy=
array([[[[ 0.49999997+0.j,  0.49999997+0.j],
         [ 0.49999997+0.j, -0.49999997+0.j]],

        [[ 0.49999997+0.j,  0.49999997+0.j],
         [ 0.49999997+0.j, -0.49999997+0.j]]],


       [[[ 0.49999997+0.j,  0.49999997+0.j],
         [ 0.49999997+0.j, -0.49999997+0.j]],

        [[-0.49999997+0.j, -0.49999997+0.j],
         [-0.49999997+0.j,  0.49999997+0.j]]]], dtype=complex64)>

In [14]:
print(HH[0,0])

tf.Tensor(
[[ 0.49999997+0.j  0.49999997+0.j]
 [ 0.49999997+0.j -0.49999997+0.j]], shape=(2, 2), dtype=complex64)


In [15]:
print(HH[1,1])

tf.Tensor(
[[-0.49999997+0.j -0.49999997+0.j]
 [-0.49999997+0.j  0.49999997+0.j]], shape=(2, 2), dtype=complex64)


In [16]:
print(HH[0,0,1,1])

tf.Tensor((-0.49999997+0j), shape=(), dtype=complex64)


# Building a (2,2,2,2) tensors corresponding to a 4x4 matrix

In [17]:
G_np=np.zeros((2,2,2,2))

In [18]:
G_np=np.asarray(
    [[
        [[1,2],[3,4]],
        [[5,6],[7,8]]],
     
    [[[9,10],[11,12]],
    [[13,14],[15,16]]
    
    ]]
    , dtype=complex)

In [19]:
G=tf.constant(G_np,dtype=tf.complex64)

In [20]:
G.shape

TensorShape([2, 2, 2, 2])

In [21]:
print(G)

tf.Tensor(
[[[[ 1.+0.j  2.+0.j]
   [ 3.+0.j  4.+0.j]]

  [[ 5.+0.j  6.+0.j]
   [ 7.+0.j  8.+0.j]]]


 [[[ 9.+0.j 10.+0.j]
   [11.+0.j 12.+0.j]]

  [[13.+0.j 14.+0.j]
   [15.+0.j 16.+0.j]]]], shape=(2, 2, 2, 2), dtype=complex64)


In [22]:
print(tf.reshape(G,[4,4]))

tf.Tensor(
[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j 11.+0.j 12.+0.j]
 [13.+0.j 14.+0.j 15.+0.j 16.+0.j]], shape=(4, 4), dtype=complex64)


In [23]:
print(tf.reshape(tf.transpose(G,perm=[1,2,0,3]),[4,4]))

tf.Tensor(
[[ 1.+0.j  2.+0.j  9.+0.j 10.+0.j]
 [ 3.+0.j  4.+0.j 11.+0.j 12.+0.j]
 [ 5.+0.j  6.+0.j 13.+0.j 14.+0.j]
 [ 7.+0.j  8.+0.j 15.+0.j 16.+0.j]], shape=(4, 4), dtype=complex64)


In [24]:
print(tf.transpose(G,perm=[1,2,0,3]))

tf.Tensor(
[[[[ 1.+0.j  2.+0.j]
   [ 9.+0.j 10.+0.j]]

  [[ 3.+0.j  4.+0.j]
   [11.+0.j 12.+0.j]]]


 [[[ 5.+0.j  6.+0.j]
   [13.+0.j 14.+0.j]]

  [[ 7.+0.j  8.+0.j]
   [15.+0.j 16.+0.j]]]], shape=(2, 2, 2, 2), dtype=complex64)


# CNOT gate

In [25]:
CNOT_np=np.zeros((2,2,2,2))
CNOT_np[0,0,0,0]=1
CNOT_np[0,0,1,1]=1
CNOT_np[1,1,0,1]=1
CNOT_np[1,1,1,0]=1

In [26]:
CNOT = tf.constant(CNOT_np,dtype=tf.complex64)

In [27]:
CNOT

<tf.Tensor: shape=(2, 2, 2, 2), dtype=complex64, numpy=
array([[[[1.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j]],

        [[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]]],


       [[[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 1.+0.j],
         [1.+0.j, 0.+0.j]]]], dtype=complex64)>

In [28]:
tf.transpose(CNOT,perm=[1,3,0,2])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=complex64, numpy=
array([[[[1.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 1.+0.j],
         [0.+0.j, 0.+0.j]]],


       [[[0.+0.j, 0.+0.j],
         [0.+0.j, 1.+0.j]],

        [[0.+0.j, 0.+0.j],
         [1.+0.j, 0.+0.j]]]], dtype=complex64)>

In [29]:
print(CNOT)
print(tf.reshape(CNOT,(4,4)))

tf.Tensor(
[[[[1.+0.j 0.+0.j]
   [0.+0.j 1.+0.j]]

  [[0.+0.j 0.+0.j]
   [0.+0.j 0.+0.j]]]


 [[[0.+0.j 0.+0.j]
   [0.+0.j 0.+0.j]]

  [[0.+0.j 1.+0.j]
   [1.+0.j 0.+0.j]]]], shape=(2, 2, 2, 2), dtype=complex64)
tf.Tensor(
[[1.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 1.+0.j 0.+0.j]], shape=(4, 4), dtype=complex64)


In [30]:
print(tf.transpose(CNOT,perm=[1,3,0,2]))
print(tf.reshape(tf.transpose(CNOT,perm=[1,2,0,3]),(4,4)))

tf.Tensor(
[[[[1.+0.j 0.+0.j]
   [0.+0.j 0.+0.j]]

  [[0.+0.j 1.+0.j]
   [0.+0.j 0.+0.j]]]


 [[[0.+0.j 0.+0.j]
   [0.+0.j 1.+0.j]]

  [[0.+0.j 0.+0.j]
   [1.+0.j 0.+0.j]]]], shape=(2, 2, 2, 2), dtype=complex64)
tf.Tensor(
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]], shape=(4, 4), dtype=complex64)


Reshape does not cust in the proper way, need to transpose some column first

In [31]:
@tf.function
def transform(A):
    """ reshape an operator as 4x4 """
    return (tf.reshape(tf.transpose(A,perm=[1,3,0,2]),(4,4)))

In [32]:
print(transform(CNOT))

tf.Tensor(
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]], shape=(4, 4), dtype=complex64)


## Test CNOT

In [33]:
print(Gate(CNOT, q00))
print(Gate(CNOT, q01))
print(Gate(CNOT, q10))
print(Gate(CNOT, q11))

tf.Tensor(
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)


# CZ gate

In [34]:
print(CZ)

tf.Tensor(
[[[[ 1.+0.j  0.+0.j]
   [ 0.+0.j  1.+0.j]]

  [[ 0.+0.j  0.+0.j]
   [ 0.+0.j  0.+0.j]]]


 [[[ 0.+0.j  0.+0.j]
   [ 0.+0.j  0.+0.j]]

  [[ 1.+0.j  0.+0.j]
   [ 0.+0.j -1.+0.j]]]], shape=(2, 2, 2, 2), dtype=complex64)


In [35]:
print(transform(CZ))

tf.Tensor(
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]], shape=(4, 4), dtype=complex64)


## Test CZ

In [36]:
print(Gate(CZ, q00))
print(Gate(CZ, q01))
print(Gate(CZ, q10))
print(Gate(CZ, q11))

tf.Tensor(
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[ 0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j]], shape=(2, 2), dtype=complex64)


In [37]:
np.set_printoptions(precision=4)
print(Gate(CZ, Gate(HH,q00)))
print(Gate(CZ, Gate(HH, q01)))
print(Gate(CZ, Gate(HH, q10)))
print(Gate(CZ, Gate(HH, q11)))

tf.Tensor(
[[ 0.5+0.j  0.5+0.j]
 [ 0.5+0.j -0.5+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[ 0.5+0.j -0.5+0.j]
 [ 0.5+0.j  0.5+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[ 0.5+0.j  0.5+0.j]
 [-0.5+0.j  0.5+0.j]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[ 0.5+0.j -0.5+0.j]
 [-0.5+0.j -0.5+0.j]], shape=(2, 2), dtype=complex64)
