# Bra and Ket with tensors and the density matrix



<img src="../logo_circular.png" width="20" height="20" />@by claudio<br>
nonlinearxwaves@gmail.com<br>


@created 1 August 2022<br>
@version 6 October 2023<br>

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # disable warning messages 

In [2]:
from thqml import quantummap as qm
import tensorflow as tf
import numpy as np
#from quomplex2021.utilities import utilities as u
import matplotlib.pyplot as plt
from matplotlib import cm

In [3]:
mytype=tf.complex64

define the type for the qubits

## Define the qbuit as an ancilla state

In [4]:
qubit0 = tf.constant([1,0],dtype=mytype)
print(qubit0)

tf.Tensor([1.+0.j 0.+0.j], shape=(2,), dtype=complex64)


In [5]:
qubit1 = tf.constant([0,1],dtype=mytype)
print(qubit1)

tf.Tensor([0.+0.j 1.+0.j], shape=(2,), dtype=complex64)


### Test the covectors for the states

In [6]:
coqubit0=tf.transpose(qubit0,conjugate=True); 
print(coqubit0)

tf.Tensor([1.-0.j 0.-0.j], shape=(2,), dtype=complex64)


In [7]:
# alternative definition of covector
coqubit0=tf.math.conj(qubit0); 
print(coqubit0)

tf.Tensor([1.-0.j 0.-0.j], shape=(2,), dtype=complex64)


In [8]:
coqubit1=tf.transpose(qubit1,conjugate=True); 
print(coqubit1)

tf.Tensor([0.-0.j 1.-0.j], shape=(2,), dtype=complex64)


### Test the scalar product

$\langle 0|0\rangle$

In [9]:
tf.tensordot(coqubit0,qubit0,axes=1)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

$\langle 1|1\rangle$

In [10]:
tf.tensordot(coqubit1,qubit1,axes=1)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

$\langle 0|1\rangle$

In [11]:
tf.tensordot(coqubit0,qubit1,axes=1)

<tf.Tensor: shape=(), dtype=complex64, numpy=0j>

$\langle 1|0\rangle$

In [12]:
tf.tensordot(coqubit1,qubit0,axes=1)

<tf.Tensor: shape=(), dtype=complex64, numpy=0j>

### Test the density matrix

$|0\rangle\langle 0|$

Note the order in the tensor dot opposite with respect to the scalar product

In [13]:
tf.tensordot(qubit0,coqubit0,axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)>

$|1\rangle\langle 1|$

In [14]:
tf.tensordot(qubit1, coqubit1,axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]], dtype=complex64)>

$|1\rangle\langle 0|$

In [15]:
tf.tensordot(qubit1,coqubit0,axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j]], dtype=complex64)>

$|0\rangle\langle 1|$

In [16]:
tf.tensordot(qubit0,coqubit1,axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j]], dtype=complex64)>

### Consider a state as a linear combination of `qubit0` and `qubit1`

In [17]:
psi=qubit0/np.sqrt(2.0)+1j*qubit1/np.sqrt(2.0)
print(psi)

tf.Tensor([0.70710677+0.j         0.        +0.70710677j], shape=(2,), dtype=complex64)


Note that in general linear combinations are not normalized

### Normalize the state

In [18]:
normpsi=tf.tensordot(tf.math.conj(psi),psi,axes=1);
print(normpsi)

tf.Tensor((0.99999994+0j), shape=(), dtype=complex64)


In [19]:
print(tf.sqrt(normpsi))

tf.Tensor((0.99999994+0j), shape=(), dtype=complex64)


In [20]:
psi=psi/tf.sqrt(normpsi);
print(psi)

tf.Tensor([0.7071068+0.j        0.       +0.7071068j], shape=(2,), dtype=complex64)


In [21]:
normpsi=tf.tensordot(tf.math.conj(psi),psi,axes=1);
print(normpsi)

tf.Tensor((1.0000001+0j), shape=(), dtype=complex64)


## Compute the covector of psi

In [22]:
copsi=tf.math.conj(psi);
print(copsi)

tf.Tensor([0.7071068-0.j        0.       -0.7071068j], shape=(2,), dtype=complex64)


### Self scalar product

In [23]:
tf.tensordot(copsi,psi, axes=1)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1.0000001+0j)>

### Density matrix

In [24]:
rho1=tf.tensordot(psi, copsi, axes=0)
print(rho1)

tf.Tensor(
[[0.50000006+0.j         0.        -0.50000006j]
 [0.        +0.50000006j 0.50000006+0.j        ]], shape=(2, 2), dtype=complex64)


### Trace of the density matrix (first version)

In [25]:
tf.linalg.trace(rho1)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1.0000001+0j)>

# Two qubits

Define $|0\rangle \otimes |0 \rangle$

In [26]:
q00 = tf.tensordot(qubit0,qubit0,axes=0);
print(q00)

tf.Tensor(
[[1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)


Define $|0\rangle \otimes |1 \rangle$

In [27]:
q01 = tf.tensordot(qubit0,qubit1,axes=0);
print(q01)

tf.Tensor(
[[0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)


Define $|1\rangle \otimes |0 \rangle$

In [28]:
q10 = tf.tensordot(qubit1,qubit0,axes=0);
print(q10)

tf.Tensor(
[[0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j]], shape=(2, 2), dtype=complex64)


Define $|1\rangle \otimes |1 \rangle$

In [29]:
q11 = tf.tensordot(qubit1,qubit1,axes=0);
print(q11)

tf.Tensor(
[[0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]], shape=(2, 2), dtype=complex64)


Linear combinations (not normalized)

In [30]:
q01+q10

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]], dtype=complex64)>

In [31]:
q00+3j*q11

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+3.j]], dtype=complex64)>

## Define a state $|\psi\rangle$

In [32]:
psiu=q00+1j*q01+(1.0+3j)*q10-2.0*q11
print(psiu)

tf.Tensor(
[[ 1.+0.j  0.+1.j]
 [ 1.+3.j -2.+0.j]], shape=(2, 2), dtype=complex64)


This state is not normalized, so we first define its dual, then compute the norm, and normalized the state

In [33]:
copsiu=tf.math.conj(psiu)
print(copsiu)

tf.Tensor(
[[ 1.-0.j  0.-1.j]
 [ 1.-3.j -2.-0.j]], shape=(2, 2), dtype=complex64)


To compute the norm we contract with the axes corresponding to qubit 0 and 1
We specify for each tensor the axes of contraction
So axes is a list of two list of indices 

In [34]:
norm2psiu=tf.tensordot(copsiu,psiu,axes=[[0,1],[0,1]])
print(norm2psiu)

tf.Tensor((16+0j), shape=(), dtype=complex64)


We now normalize the state with the sqrt of the norm

In [35]:
psi=psiu/tf.sqrt(norm2psiu)
print(psi)

tf.Tensor(
[[ 0.25+0.j    0.  +0.25j]
 [ 0.25+0.75j -0.5 +0.j  ]], shape=(2, 2), dtype=complex64)


We compute the dual

In [36]:
copsi=tf.math.conj(psi)

And we compute again the norm to check normalization

In [37]:
tf.tensordot(copsi,psi,axes=[[0,1],[0,1]])

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

We also check the normalization with the scalar 2 functions

In [38]:
qm.Scalar2(psi,psi)

<tf.Tensor: shape=(1, 1), dtype=complex64, numpy=array([[1.+0.j]], dtype=complex64)>

To check let us redefine manually the tensor

In [39]:
psi=0.25*q00+0.25*1j*q01+0.25*(1.0+3j)*q10-0.5*q11
print(psi)

tf.Tensor(
[[ 0.25+0.j    0.  +0.25j]
 [ 0.25+0.75j -0.5 +0.j  ]], shape=(2, 2), dtype=complex64)


In [40]:
copsi=tf.math.conj(psi)
print(copsi)

tf.Tensor(
[[ 0.25-0.j    0.  -0.25j]
 [ 0.25-0.75j -0.5 -0.j  ]], shape=(2, 2), dtype=complex64)


In [41]:
tf.tensordot(copsi,psi,axes=[[0, 1],[0,1]])

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

## Now compute the density matrix

note the order in the <code>tensordot</code>

In [42]:
rho=tf.tensordot(psi,copsi,axes=0);
print(rho)

tf.Tensor(
[[[[ 0.0625+0.j      0.    -0.0625j]
   [ 0.0625-0.1875j -0.125 +0.j    ]]

  [[ 0.    +0.0625j  0.0625+0.j    ]
   [ 0.1875+0.0625j  0.    -0.125j ]]]


 [[[ 0.0625+0.1875j  0.1875-0.0625j]
   [ 0.625 +0.j     -0.125 -0.375j ]]

  [[-0.125 +0.j      0.    +0.125j ]
   [-0.125 +0.375j   0.25  +0.j    ]]]], shape=(2, 2, 2, 2), dtype=complex64)


The overal density matrix has 16 complex elements with shape (2,2,2,2)

Access the elements of rho

In [43]:
print(rho[0,0,0,0])

tf.Tensor((0.0625+0j), shape=(), dtype=complex64)


In [44]:
print(rho[1,0,0,1])

tf.Tensor((0.1875-0.0625j), shape=(), dtype=complex64)


In [45]:
print(rho[1,0,1,1])

tf.Tensor((-0.125-0.375j), shape=(), dtype=complex64)


In [46]:
print(rho[1,1,0,0])

tf.Tensor((-0.125+0j), shape=(), dtype=complex64)


In [47]:
print(rho[0,1,0,0])

tf.Tensor(0.0625j, shape=(), dtype=complex64)


In [48]:
print(rho[0,0,1,0])

tf.Tensor((0.0625-0.1875j), shape=(), dtype=complex64)


## We compute the trace by summing over specific indices

For high dimensional tensors, we need to use <code>tf.einsum</code>

trace of the one-qubit density matrix

In [49]:
tf.einsum('uu',rho1)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1.0000001+0j)>

check that the letter in <code>tf.einsum</code> is not significant

In [50]:
tf.einsum('ii',rho1)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1.0000001+0j)>

trace of two-qubit density matrix

In [51]:
tf.einsum('uvuv',rho)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

## Partial trace of the density matrix on the first qubit

In [52]:
rhoB=tf.einsum('iuiv',rho);
print(rhoB)

tf.Tensor(
[[ 0.6875+0.j     -0.125 -0.4375j]
 [-0.125 +0.4375j  0.3125+0.j    ]], shape=(2, 2), dtype=complex64)


we check that the trace of the partial trace is unitary

In [53]:
tf.einsum('vv',rhoB)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

as <code>rhoB</code> is a matrix we can also use <code>linalg.trace</code> 

In [54]:
tf.linalg.trace(rhoB)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

## Partial trace of the density matrix on the second qubit

In [55]:
rhoA=tf.einsum('xuyu',rho);
print(rhoA)

tf.Tensor(
[[0.125 +0.j     0.0625-0.3125j]
 [0.0625+0.3125j 0.875 +0.j    ]], shape=(2, 2), dtype=complex64)


In [56]:
tf.einsum('uu',rhoA)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

In [57]:
tf.linalg.trace(rhoA)

<tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>

## Compute the degree of entanglement by the eigenvalues

### Eigenvalues of the system one-qubit rho

In [58]:
rho1_np=rho1.numpy()

In [59]:
np.linalg.eig(rho1_np)[0]

array([1.0000001+0.j, 0.       +0.j], dtype=complex64)

As we have one unitary and one zero eigenvalue, the state is a pure state, as expected

### Eigenvalues of the two-qubit rho

as rho for two qubit is not matrix, we shoud recast rho as a matrix and the compute the eigenvalues

### Eigenvalues of the system rhoA

In [60]:
eA=tf.linalg.eig(rhoA); print(eA[0])

tf.Tensor([0.00787451-4.8248174e-09j 0.9921254 +4.8248174e-09j], shape=(2,), dtype=complex64)


The imaginary part must be zero within numerical errors

The eigenvalues correspond to the probabiliets <code>p</code>

Compute the von Neuman entropy

In [61]:
eAr=np.real(eA[0].numpy());

In [62]:
-eAr[0]*np.log2(eAr[0])-eAr[1]*np.log2(eAr[1])

0.06634756

### Eigenvalues of the system rhoB

In [63]:
eB=tf.linalg.eig(rhoB); print(eB[0])

tf.Tensor([0.00787451+1.5521238e-08j 0.9921255 -2.2971818e-08j], shape=(2,), dtype=complex64)


The imaginary part must be zero within numerical errors

Compute the von Neuman entropy

In [64]:
eBr=np.real(eB[0].numpy())
-eBr[0]*np.log2(eBr[0])-eBr[1]*np.log2(eBr[1])

0.0663474

As expected the two entropy are the same, and the system is entangled

### Compute the orthonormal basis

In [65]:
eA

(<tf.Tensor: shape=(2,), dtype=complex64, numpy=
 array([0.00787451-4.8248174e-09j, 0.9921254 +4.8248174e-09j],
       dtype=complex64)>,
 <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
 array([[-0.9386162 +0.0000000e+00j,  0.34496322+1.2747664e-08j],
        [ 0.06765284+3.3826429e-01j,  0.18407774+9.2038894e-01j]],
       dtype=complex64)>)

In [66]:
eB

(<tf.Tensor: shape=(2,), dtype=complex64, numpy=
 array([0.00787451+1.5521238e-08j, 0.9921255 -2.2971818e-08j],
       dtype=complex64)>,
 <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
 array([[-0.55632716+3.2900608e-08j,  0.83096343+0.0000000e+00j],
        [-0.22828314+7.9899126e-01j, -0.15283479+5.3492188e-01j]],
       dtype=complex64)>)

# Principal values of Psi

Compute the principal values of the two qubit vector

In [67]:
d=tf.linalg.svd(psi,compute_uv=False)
print(d)

tf.Tensor([0.996055   0.08873843], shape=(2,), dtype=float32)


Compute the propbabilities

In [68]:
# we determine the probabilities and the convert to numbpy to use np.log2
p=(tf.abs(d)**2).numpy()
print(p)

[0.9921256  0.00787451]


Compute the entanglement entropy

In [69]:
-p[0]*np.log2(p[0])-p[1]*np.log2(p[1])

0.0663473

We can also use <code>tf.math.log</code> but we have to account for the basis of the log

In [70]:
-p[0]*tf.math.log(p[0])-p[1]*tf.math.log(p[1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.04598844>

this result is different because the log is in the natural basis

Let us normalize to log(2.0) and we get the same result

In [71]:
(-p[0]*tf.math.log(p[0])-p[1]*tf.math.log(p[1]))/tf.math.log(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.06634729>

# Compute the orthonormal basis by SVD

In [72]:
d, U, V=tf.linalg.svd(psi)

In [73]:
VH=tf.transpose(V, conjugate=True)

print the matrix u

In [74]:
print(U)

tf.Tensor(
[[-0.05729683+0.34017158j  0.43057674+0.8340288j ]
 [-0.9381789 +0.02864844j  0.26953763-0.21528839j]], shape=(2, 2), dtype=complex64)


In [75]:
print(VH)

tf.Tensor(
[[-0.22828318-0.7989912j  0.5563271 -0.j       ]
 [ 0.15283479+0.5349218j  0.83096343-0.j       ]], shape=(2, 2), dtype=complex64)


check if V is unitary

In [76]:
tf.tensordot(VH,V,axes=1)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[1.0000000e+00+0.j, 2.9802322e-08+0.j],
       [2.9802322e-08+0.j, 1.0000000e+00+0.j]], dtype=complex64)>

compute the elements of the new basis

In [77]:
u0=U[:,0]
u1=U[:,1]
print(u0)
print(u1)

tf.Tensor([-0.05729683+0.34017158j -0.9381789 +0.02864844j], shape=(2,), dtype=complex64)
tf.Tensor([0.43057674+0.8340288j  0.26953763-0.21528839j], shape=(2,), dtype=complex64)


In [78]:
v0=VH[0,:]
v1=VH[1,:]
print(v0)
print(v1)

tf.Tensor([-0.22828318-0.7989912j  0.5563271 -0.j       ], shape=(2,), dtype=complex64)
tf.Tensor([0.15283479+0.5349218j 0.83096343-0.j       ], shape=(2,), dtype=complex64)


### Other strategy, returns the compontens by contracting the proper indices

define a list of the one-qubit basis

In [79]:
basis=[qubit0,qubit1]

contract with the first index of U

In [80]:
ucomponents=tf.tensordot(U,basis,[[0],[0]])

component of u0

In [81]:
ucomponents[0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.05729683+0.34017158j, -0.9381789 +0.02864844j], dtype=complex64)>

In [82]:
ucomponents[1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.43057674+0.8340288j , 0.26953763-0.21528839j], dtype=complex64)>

In [83]:
vcomponents=tf.tensordot(VH,basis,[[1],[0]])

In [84]:
vcomponents[0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.22828318-0.7989912j,  0.5563271 +0.j       ], dtype=complex64)>

In [85]:
vcomponents[1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.15283479+0.5349218j, 0.83096343+0.j       ], dtype=complex64)>

### Components of the reduced density matrix

$|u_0\rangle\langle u_0|$

In [86]:
print(tf.tensordot(U[:,0],tf.math.conj(U[:,0]),axes=0))

tf.Tensor(
[[0.11899963+0.j         0.06350006-0.31750035j]
 [0.06350006+0.31750035j 0.8810004 +0.j        ]], shape=(2, 2), dtype=complex64)


$|u_1\rangle\langle u_1|$

In [87]:
print(tf.tensordot(U[:,1],tf.math.conj(U[:,1]),axes=0))

tf.Tensor(
[[ 0.88100034+0.j        -0.06350008+0.3175003j]
 [-0.06350008-0.3175003j  0.11899962+0.j       ]], shape=(2, 2), dtype=complex64)


$|v_0\rangle\langle v_0|$

In [88]:
print(tf.tensordot(VH[:,0],tf.math.conj(VH[:,0]),axes=0))

tf.Tensor(
[[ 0.6905002 +0.j -0.46228746+0.j]
 [-0.46228746+0.j  0.30949983+0.j]], shape=(2, 2), dtype=complex64)


$|v_1\rangle\langle v_1|$

In [89]:
print(tf.tensordot(VH[:,1],tf.math.conj(VH[:,1]),axes=0))

tf.Tensor(
[[0.30949986+0.j 0.4622875 +0.j]
 [0.4622875 +0.j 0.6905002 +0.j]], shape=(2, 2), dtype=complex64)


### Compare with the diagonalization of the density matrix

In [90]:
print(eA[0])

tf.Tensor([0.00787451-4.8248174e-09j 0.9921254 +4.8248174e-09j], shape=(2,), dtype=complex64)


In [91]:
print(eA[1])

tf.Tensor(
[[-0.9386162 +0.0000000e+00j  0.34496322+1.2747664e-08j]
 [ 0.06765284+3.3826429e-01j  0.18407774+9.2038894e-01j]], shape=(2, 2), dtype=complex64)


Compare the decomposition by diagonalizing rhoA and rhoB, with U and V

In [92]:
print(tf.tensordot(U[:,1],tf.math.conj(U[:,1]),axes=0))
print(tf.tensordot(U[:,0],tf.math.conj(U[:,0]),axes=0))

tf.Tensor(
[[ 0.88100034+0.j        -0.06350008+0.3175003j]
 [-0.06350008-0.3175003j  0.11899962+0.j       ]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.11899963+0.j         0.06350006-0.31750035j]
 [0.06350006+0.31750035j 0.8810004 +0.j        ]], shape=(2, 2), dtype=complex64)


In [93]:
print(tf.tensordot(eA[1][:,0],tf.math.conj(eA[1][:,0]),axes=0))
print(tf.tensordot(U[:,1],tf.math.conj(U[:,1]),axes=0))

tf.Tensor(
[[ 0.8810004 +0.j         -0.06350005+0.31750035j]
 [-0.06350005-0.31750035j  0.11899964+0.j        ]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[ 0.88100034+0.j        -0.06350008+0.3175003j]
 [-0.06350008-0.3175003j  0.11899962+0.j       ]], shape=(2, 2), dtype=complex64)


In [94]:
print(tf.tensordot(eA[1][:,1],tf.math.conj(eA[1][:,1]),axes=0))
print(tf.tensordot(U[:,0],tf.math.conj(U[:,0]),axes=0))

tf.Tensor(
[[0.11899962+0.j         0.06350006-0.31750032j]
 [0.06350006+0.31750032j 0.8810004 +0.j        ]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.11899963+0.j         0.06350006-0.31750035j]
 [0.06350006+0.31750035j 0.8810004 +0.j        ]], shape=(2, 2), dtype=complex64)


In [95]:
print(eB[0])

tf.Tensor([0.00787451+1.5521238e-08j 0.9921255 -2.2971818e-08j], shape=(2,), dtype=complex64)


In [96]:
print(eB[1])

tf.Tensor(
[[-0.55632716+3.2900608e-08j  0.83096343+0.0000000e+00j]
 [-0.22828314+7.9899126e-01j -0.15283479+5.3492188e-01j]], shape=(2, 2), dtype=complex64)


In [97]:
print(tf.tensordot(eB[1][:,0],tf.math.conj(eB[1][:,0]),axes=0))
print(tf.tensordot(VH[1,:],tf.math.conj(VH[1,:]),axes=0))

tf.Tensor(
[[0.30949992+0.j         0.12700014+0.44450054j]
 [0.12700014-0.44450054j 0.6905002 +0.j        ]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[0.30949983+0.j         0.12700012+0.44450048j]
 [0.12700012-0.44450048j 0.6905002 +0.j        ]], shape=(2, 2), dtype=complex64)


In [98]:
print(tf.tensordot(eB[1][:,1],tf.math.conj(eB[1][:,1]),axes=0))
print(tf.tensordot(VH[:,0],tf.math.conj(VH[:,0]),axes=0))

tf.Tensor(
[[ 0.6905002 +0.j         -0.12700012-0.44450054j]
 [-0.12700012+0.44450054j  0.3094999 +0.j        ]], shape=(2, 2), dtype=complex64)
tf.Tensor(
[[ 0.6905002 +0.j -0.46228746+0.j]
 [-0.46228746+0.j  0.30949983+0.j]], shape=(2, 2), dtype=complex64)


### Check the rebuild of rhoB by eigenvector

In [99]:
rhoB

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[ 0.6875+0.j    , -0.125 -0.4375j],
       [-0.125 +0.4375j,  0.3125+0.j    ]], dtype=complex64)>

In [100]:
eB[0][1]*tf.tensordot(eB[1][:,1],tf.math.conj(eB[1][:,1]),axes=0)+eB[0][0]*tf.tensordot(eB[1][:,0],tf.math.conj(eB[1][:,0]),axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[ 0.68750006-1.1058225e-08j, -0.12500001-4.3750009e-01j],
       [-0.12499998+4.3750009e-01j,  0.3125001 +3.6076431e-09j]],
      dtype=complex64)>

In [101]:
pr=tf.constant(tf.complex(d**2,0*d),dtype=tf.complex64)
print(pr)

tf.Tensor([0.9921256 +0.j 0.00787451+0.j], shape=(2,), dtype=complex64)


In [102]:
pr[0]*tf.tensordot(V[:,0],tf.math.conj(V[:,0]),axes=0)+pr[1]*tf.tensordot(V[:,0],tf.math.conj(V[:,0]),axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[ 0.69050026+0.j       , -0.12700014+0.4445005j],
       [-0.12700014-0.4445005j,  0.30949986+0.j       ]], dtype=complex64)>

In [103]:
rhoA

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[0.125 +0.j    , 0.0625-0.3125j],
       [0.0625+0.3125j, 0.875 +0.j    ]], dtype=complex64)>

In [104]:
pr[0]*tf.tensordot(U[:,0],tf.math.conj(U[:,0]),axes=0)+pr[1]*tf.tensordot(U[:,0],tf.math.conj(U[:,0]),axes=0)

<tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
array([[0.11899965+0.j        , 0.06350007-0.31750035j],
       [0.06350007+0.31750035j, 0.88100046+0.j        ]], dtype=complex64)>

# Define a function that returns the von Neumann entropy for a two qubit

In [105]:
@tf.function
def VonNeumannEntropy2(psi):
    """ Return the entanglement entropy for a two-qubit
    with tensor (2,2) psi 
    Return the entropy and 
    the squared principal values pr
    """
    d=tf.linalg.svd(psi,compute_uv=False)
    d2=tf.abs(d)**2
    logd2=tf.math.log(d2+1e-12)/tf.math.log(2.0)
    return tf.reduce_sum(-d2*logd2),d2

In [106]:
tf.print(VonNeumannEntropy2(psi))

(0.0663472936, [0.992125571 0.00787450839])


# Compute entanglement for a product state

define a product state

In [107]:
phiA=(qubit0+1j*qubit1)/np.sqrt(2.0)

In [108]:
print(phiA)

tf.Tensor([0.70710677+0.j         0.        +0.70710677j], shape=(2,), dtype=complex64)


In [109]:
phiB=qubit1

In [110]:
phi=tf.tensordot(phiA,phiB,axes=0)
print(phi)

tf.Tensor(
[[0.        +0.j         0.70710677+0.j        ]
 [0.        +0.j         0.        +0.70710677j]], shape=(2, 2), dtype=complex64)


In [111]:
tf.print(VonNeumannEntropy2(phi))

(1.71982634e-07, [0.999999881 0])


# Compute entanglement for a maximally entangled state

In [112]:
PHIplus=(q00+q11)/np.sqrt(2.0)

In [113]:
tf.print(VonNeumannEntropy2(PHIplus))

(1, [0.49999997 0.49999997])


In [114]:
PHIminus=(q00-q11)/np.sqrt(2.0)
tf.print(VonNeumannEntropy2(PHIminus))

(1, [0.49999997 0.49999997])


In [115]:
PSIplus=(q01+q10)/np.sqrt(2.0)

In [116]:
tf.print(VonNeumannEntropy2(PSIplus))

(1, [0.49999997 0.49999997])


In [117]:
PSIminus=(q01-q10)/np.sqrt(2.0)
tf.print(VonNeumannEntropy2(PSIminus))

(1, [0.49999997 0.49999997])


# SVD for a maximally entangled state

In [118]:
dm, Um, Vm=tf.linalg.svd(PHIplus)
VHm=tf.transpose(Vm, conjugate=True)

In [119]:
print(dm)

tf.Tensor([0.70710677 0.70710677], shape=(2,), dtype=float32)


In [120]:
Um[:,0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.+0.j, 0.+0.j], dtype=complex64)>

In [121]:
Um[:,1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.+0.j, 1.+0.j], dtype=complex64)>

In [122]:
VHm[0,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.-0.j, 0.-0.j], dtype=complex64)>

In [123]:
VHm[1,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.-0.j, 1.-0.j], dtype=complex64)>

In [124]:
dm, Um, Vm=tf.linalg.svd(PSIplus)
VHm=tf.transpose(Vm, conjugate=True)

In [125]:
Um[:,0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.-0.j,  1.-0.j], dtype=complex64)>

In [126]:
Um[:,1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.+0.j, 0.+0.j], dtype=complex64)>

In [127]:
VHm[0,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.-0.j, 0.-0.j], dtype=complex64)>

In [128]:
VHm[1,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.-0.j, 1.-0.j], dtype=complex64)>

In [129]:
dm, Um, Vm=tf.linalg.svd(PSIminus)
VHm=tf.transpose(Vm, conjugate=True)

In [130]:
Um[:,0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([ 0.+0.j, -1.+0.j], dtype=complex64)>

In [131]:
Um[:,1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.+0.j, 0.+0.j], dtype=complex64)>

In [132]:
VHm[0,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.-0.j, 0.-0.j], dtype=complex64)>

In [133]:
VHm[1,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.-0.j, 1.-0.j], dtype=complex64)>

In [134]:
dm, Um, Vm=tf.linalg.svd(PHIminus)
VHm=tf.transpose(Vm, conjugate=True)

In [135]:
Um[:,0]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.+0.j, 0.+0.j], dtype=complex64)>

In [136]:
Um[:,1]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.-0.j, -1.-0.j], dtype=complex64)>

In [137]:
VHm[0,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([1.-0.j, 0.-0.j], dtype=complex64)>

In [138]:
VHm[1,:]

<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([0.-0.j, 1.-0.j], dtype=complex64)>