# Some remarks on tensors and vectors in TensorFlow

<img src="../logo_circular.png" width="20" height="20" />@by claudio<br>
nonlinearxwaves@gmail.com<br>


@created 25 June 2022<br>
@version 6 October 2023<br>

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # disable warning messages 

In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm

In [3]:
mytype=tf.complex64

# Define a column vector as a list of numbers

$V=\begin{pmatrix}V^0\\V^1\end{pmatrix}=\begin{pmatrix}1.0\\2.0\end{pmatrix}$

Note we use contravariant indices for vectors

In [4]:
V=tf.constant([1.0, 2.0])
print(V)

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


Note the shape is (2,)

V[0] and V[1] are the elements of the list with empty shape

In [5]:
print(V[0])

tf.Tensor(1.0, shape=(), dtype=float32)


In [6]:
print(V[1])

tf.Tensor(2.0, shape=(), dtype=float32)


`tf.print` returns the elements with no information on the shape (but does not handle tf.complex type)

In [7]:
tf.print(V)

[1 2]


In [8]:
tf.print(V[0])

1


In [9]:
tf.print(V[1])

2


# Define a matrix as a shape=(2,2) tensor

$M=\left(\begin{array}{cc}M^0{}_0{} & M^0{}_1{}\\M^1{}_0{} & M^1{}_1{}\end{array}\right)=\left(\begin{array}{cc}3.0  & 4.0\\5.0 & 6.0\end{array}\right)$

In [10]:
M=tf.constant([[3.0,4.0],[5.0,6.0]])

In [11]:
print(M)

tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [12]:
tf.print(M)

[[3 4]
 [5 6]]


## Access the rows of the matrix as the sublists

In [13]:
print(M[0])

tf.Tensor([3. 4.], shape=(2,), dtype=float32)


In [14]:
tf.print(M[0])

[3 4]


In [15]:
print(M[1])

tf.Tensor([5. 6.], shape=(2,), dtype=float32)


In [16]:
tf.print(M[1])

[5 6]


## Access the columns

In [17]:
print(M[:,0])

tf.Tensor([3. 5.], shape=(2,), dtype=float32)


In [18]:
print(M[:,1])

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


## Access the elements of the matrix

In [19]:
M[0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [20]:
tf.print(M[0,0])

3


In [21]:
M[0,1]

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [22]:
M[1,0]

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [23]:
M[1,1]

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

# Outer product of M and V

In [24]:
outerMV=tf.tensordot(M,V,axes=0)

In [25]:
print(outerMV[0,0,1])

tf.Tensor(6.0, shape=(), dtype=float32)


In [26]:
tf.print(outerMV)

[[[3 6]
  [4 8]]

 [[5 10]
  [6 12]]]


In [27]:
tf.print(outerMV[0,0,1])

6


# Inner Product of matrix and vector

Contraction of the outer product $M^i{}_j{} V^k$ with respect to indices $j$ and $k$

In [28]:
innerMV=tf.tensordot(M,V,axes=[1,0])

This is equivalent to the matrix vector multiplication $M^i{}_j{} V^j$

In [29]:
print(innerMV)

tf.Tensor([11. 17.], shape=(2,), dtype=float32)


In [30]:
tf.tensordot(M,V,axes=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([11., 17.], dtype=float32)>

This a simplified notation for the matrix vector multiplication

# Define the column and row vectors as tensors with shape (1,2) or (2,1)

In [31]:
VR=tf.constant([1.0, 2.0],shape=(1,2))

In [32]:
print(VR)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)


In [33]:
tf.print(VR)

[[1 2]]


In [34]:
print(VR[0])

tf.Tensor([1. 2.], shape=(2,), dtype=float32)


In [35]:
tf.print(VR[0])

[1 2]


In [36]:
print(VR[0,0])

tf.Tensor(1.0, shape=(), dtype=float32)


In [37]:
print(VR[0,1])

tf.Tensor(2.0, shape=(), dtype=float32)


In [38]:
VC=tf.constant([1.0, 2.0],shape=(2,1))

In [39]:
print(VC)

tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)


In [40]:
print(VC[0])

tf.Tensor([1.], shape=(1,), dtype=float32)


In [41]:
print(VC[1])

tf.Tensor([2.], shape=(1,), dtype=float32)


In [42]:
print(VC[0,0])

tf.Tensor(1.0, shape=(), dtype=float32)


In [43]:
print(VC[1,0])

tf.Tensor(2.0, shape=(), dtype=float32)


# Inner product with shape (2,2) and (2,1)

In [44]:
tf.tensordot(M,VC,axes=[1,0])

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[11.],
       [17.]], dtype=float32)>

In [45]:
tf.tensordot(M,VC,axes=1)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[11.],
       [17.]], dtype=float32)>

In [46]:
tf.tensordot(M,VR,axes=[1,1])

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[11.],
       [17.]], dtype=float32)>