# Test the generation of symplectic matrices
Test the formulas concerning RP, RQ, J, and M


<img src="../img/logo_circular.png" width="20" height="20" />@by claudio<br>

nonlinearxwaves@gmail.com<br>
@created 12 sep 2020<br>
@version 15 may 2023

In [1]:
import numpy as np
from thqml import phasespace as ps
from thqml.utilities import utilities
import tensorflow as tf

2023-05-14 11:21:18.401010: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-14 11:21:18.401034: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
N=10

## Verifies the properties of RQ, RP and J

In [3]:
RQ, RP, J = ps.RQRP(N)

In [4]:
tf.print(RQ)

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)


2023-05-14 11:21:20.882472: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-05-14 11:21:20.882497: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-05-14 11:21:20.882519: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (x1): /proc/driver/nvidia/version does not exist
2023-05-14 11:21:20.883025: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
tf.print(RP)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)


In [6]:
RQ.shape

(10, 5)

In [7]:
RP.shape

(10, 5)

In [8]:
tf.print(J)

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.]], dtype=float32)


In [9]:
J.shape

(10, 10)

$${\bf J} {\bf R}_\text{q} = -{\bf R}_\text{p}$$

In [10]:
np.matmul(J,RQ)

array([[ 0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.]], dtype=float32)

$${\bf R}_\text{q}{\bf R}_\text{q}^\top+{\bf R}_\text{p}{\bf R}_\text{p}^\top = {\bf 1}_N$$

In [11]:
np.matmul(RQ,RQ.transpose())+np.matmul(RP,RP.transpose())

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

$${\bf R}_\text{q}{\bf R}_\text{p}^\top-{\bf R}_\text{p}{\bf R}_\text{q}^\top = {\bf J}$$

In [12]:
np.matmul(RQ,RP.transpose())-np.matmul(RP,RQ.transpose())

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.]], dtype=float32)

$${\bf R}_\text{p}^\top {\bf R}_\text{q} = {\bf 0}_{n}$$

In [13]:
np.matmul(RP.transpose(), RQ)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

$${\bf R}_\text{q}^\top {\bf R}_\text{q} = {\bf 1}_{n}$$

In [14]:
np.matmul(RQ.transpose(), RQ)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

## Verify the symplectic matrix

In [15]:
M, MI, U = ps.RandomSymplectic(N)

In [16]:
tf.print(M)

array([[ 0.33442115,  0.35201558, -0.10746386,  0.26402261, -0.41732781,
         0.59593333,  0.0962469 , -0.08810987,  0.36878297, -0.02577538],
       [-0.35201558,  0.33442115, -0.26402261, -0.10746386, -0.59593333,
        -0.41732781,  0.08810987,  0.0962469 ,  0.02577538,  0.36878297],
       [-0.15915445,  0.35543689,  0.70193224,  0.4407444 , -0.08672281,
        -0.05222372, -0.30904258,  0.09463725, -0.21491739,  0.02165212],
       [-0.35543689, -0.15915445, -0.4407444 ,  0.70193224,  0.05222372,
        -0.08672281, -0.09463725, -0.30904258, -0.02165212, -0.21491739],
       [ 0.4739208 ,  0.47169526, -0.31209531,  0.19624395,  0.44895935,
        -0.22268846, -0.04688832,  0.02600138, -0.20060911,  0.35030591],
       [-0.47169526,  0.4739208 , -0.19624395, -0.31209531,  0.22268846,
         0.44895935, -0.02600138, -0.04688832, -0.35030591, -0.20060911],
       [-0.15487619, -0.1107411 ,  0.03787045,  0.30656642,  0.1136091 ,
         0.17163952,  0.69769278,  0.54159166

In [17]:
utilities.printonscreennp(MI)

+0.3+0.0i -0.4+0.0i -0.2+0.0i -0.4+0.0i +0.5+0.0i -0.5+0.0i -0.2+0.0i +0.1+0.0i -0.4+0.0i +0.1+0.0i 
+0.4+0.0i +0.3+0.0i +0.4+0.0i -0.2+0.0i +0.5+0.0i +0.5+0.0i -0.1+0.0i -0.2+0.0i -0.1+0.0i -0.4+0.0i 
-0.1+0.0i -0.3+0.0i +0.7+0.0i -0.4+0.0i -0.3+0.0i -0.2+0.0i +0.0+0.0i -0.3+0.0i +0.0+0.0i -0.0+0.0i 
+0.3+0.0i -0.1+0.0i +0.4+0.0i +0.7+0.0i +0.2+0.0i -0.3+0.0i +0.3+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
-0.4+0.0i -0.6+0.0i -0.1+0.0i +0.1+0.0i +0.4+0.0i +0.2+0.0i +0.1+0.0i -0.2+0.0i +0.3+0.0i -0.2+0.0i 
+0.6+0.0i -0.4+0.0i -0.1+0.0i -0.1+0.0i -0.2+0.0i +0.4+0.0i +0.2+0.0i +0.1+0.0i +0.2+0.0i +0.3+0.0i 
+0.1+0.0i +0.1+0.0i -0.3+0.0i -0.1+0.0i -0.0+0.0i -0.0+0.0i +0.7+0.0i -0.5+0.0i -0.3+0.0i -0.1+0.0i 
-0.1+0.0i +0.1+0.0i +0.1+0.0i -0.3+0.0i +0.0+0.0i -0.0+0.0i +0.5+0.0i +0.7+0.0i +0.1+0.0i -0.3+0.0i 
+0.4+0.0i +0.0+0.0i -0.2+0.0i -0.0+0.0i -0.2+0.0i -0.4+0.0i -0.2+0.0i -0.1+0.0i +0.5+0.0i -0.6+0.0i 
-0.0+0.0i +0.4+0.0i +0.0+0.0i -0.2+0.0i +0.4+0.0i -0.2+0.0i +0.1+0.0i -0.2+0.0i +0.6+0.0i +

In [18]:
M.shape

(10, 10)

In [19]:
MI.shape

(10, 10)

$${\bf M}{\bf M_I}={\bf 1}_N$$

In [20]:
utilities.printonscreennp(np.matmul(M,MI))

+1.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
-0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i 
-0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i 
+0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +

$${\bf M}{\bf J}{\bf M}^\top={\bf J}$$

In [21]:
utilities.printonscreennp(np.matmul(M, np.matmul(J,M.transpose()) ))

+0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
-1.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i -0.0+0.0i -1.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
-0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i 
+0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -1.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i 
-0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -1.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i 
+0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i 
-0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -1.0+0.0i +

## Verify the properties of the unitary matrix

In [22]:
utilities.printonscreennp(U)

+0.3-0.4i -0.1-0.3i -0.4-0.6i +0.1+0.1i +0.4+0.0i 
-0.2-0.4i +0.7-0.4i -0.1+0.1i -0.3-0.1i -0.2-0.0i 
+0.5-0.5i -0.3-0.2i +0.4+0.2i -0.0-0.0i -0.2-0.4i 
-0.2+0.1i +0.0-0.3i +0.1-0.2i +0.7-0.5i -0.2-0.1i 
-0.4+0.1i +0.0-0.0i +0.3-0.2i -0.3-0.1i +0.5-0.6i 


$${\bf U}^\dagger = ({\bf U}^\top)^*$$

In [23]:
Udagger =U.transpose().conjugate(); utilities.printonscreennp(Udagger)

+0.3+0.4i -0.2+0.4i +0.5+0.5i -0.2-0.1i -0.4-0.1i 
-0.1+0.3i +0.7+0.4i -0.3+0.2i +0.0+0.3i +0.0+0.0i 
-0.4+0.6i -0.1-0.1i +0.4-0.2i +0.1+0.2i +0.3+0.2i 
+0.1-0.1i -0.3+0.1i -0.0+0.0i +0.7+0.5i -0.3+0.1i 
+0.4-0.0i -0.2+0.0i -0.2+0.4i -0.2+0.1i +0.5+0.6i 


$${\bf U}^\dagger {\bf U}={\bf 1}_{n}$$

In [24]:
utilities.printonscreennp(np.matmul(Udagger,U))

+1.0+0.0i +0.0+0.0i -0.0+0.0i -0.0-0.0i -0.0-0.0i 
+0.0-0.0i +1.0+0.0i -0.0-0.0i +0.0+0.0i +0.0+0.0i 
-0.0-0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0-0.0i +0.0-0.0i +1.0+0.0i -0.0-0.0i 
-0.0+0.0i +0.0-0.0i -0.0+0.0i -0.0+0.0i +1.0+0.0i 


$${\bf U}_R=\Re{\bf U}$$

In [25]:
UR = np.real(U); utilities.printonscreennp(UR)

+0.3+0.0i -0.1+0.0i -0.4+0.0i +0.1+0.0i +0.4+0.0i 
-0.2+0.0i +0.7+0.0i -0.1+0.0i -0.3+0.0i -0.2+0.0i 
+0.5+0.0i -0.3+0.0i +0.4+0.0i -0.0+0.0i -0.2+0.0i 
-0.2+0.0i +0.0+0.0i +0.1+0.0i +0.7+0.0i -0.2+0.0i 
-0.4+0.0i +0.0+0.0i +0.3+0.0i -0.3+0.0i +0.5+0.0i 


$${\bf U}_I=\Im {\bf U}$$

In [26]:
UI = np.imag(U); utilities.printonscreennp(UI)

-0.4+0.0i -0.3+0.0i -0.6+0.0i +0.1+0.0i +0.0+0.0i 
-0.4+0.0i -0.4+0.0i +0.1+0.0i -0.1+0.0i -0.0+0.0i 
-0.5+0.0i -0.2+0.0i +0.2+0.0i -0.0+0.0i -0.4+0.0i 
+0.1+0.0i -0.3+0.0i -0.2+0.0i -0.5+0.0i -0.1+0.0i 
+0.1+0.0i -0.0+0.0i -0.2+0.0i -0.1+0.0i -0.6+0.0i 


$${\bf U}_R {\bf U}_R^\top+{\bf U}_I{\bf U}_I^\top={\bf 1}_{n}$$

In [27]:
utilities.printonscreennp(np.matmul(UR,UR.transpose())+np.matmul(UI,UI.transpose()))

+1.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i -0.0+0.0i 
+0.0+0.0i -0.0+0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +1.0+0.0i 


$${\bf U}_R {\bf U}_I^\top-{\bf U}_I{\bf U}_R^\top={\bf 0}_{n}$$

In [28]:
utilities.printonscreennp(np.matmul(UR,UI.transpose())-np.matmul(UI,UR.transpose()))

+0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i 
+0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
-0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
