# Test the generation of symplectic matrices
Test the formulas concerning RP, RQ, J, and M


<img src="../img/logo_circular.png" width="20" height="20" />@by claudio<br>

nonlinearxwaves@gmail.com<br>
@created 12 sep 2020<br>
@version 23 sep 2023

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # disable warning messages

In [2]:
import numpy as np
from thqml import phasespace as ps
from thqml.utilities import utilities
import tensorflow as tf

In [3]:
N=10

## Verifies the properties of RQ, RP and J

In [4]:
RQ, RP, J = ps.RQRP(N)

In [5]:
tf.print(RQ)

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]], dtype=float32)


In [6]:
tf.print(RP)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)


In [7]:
RQ.shape

(10, 5)

In [8]:
RP.shape

(10, 5)

In [9]:
tf.print(J)

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.]], dtype=float32)


In [10]:
J.shape

(10, 10)

$${\bf J} {\bf R}_\text{q} = -{\bf R}_\text{p}$$

In [11]:
np.matmul(J,RQ)

array([[ 0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.]], dtype=float32)

$${\bf R}_\text{q}{\bf R}_\text{q}^\top+{\bf R}_\text{p}{\bf R}_\text{p}^\top = {\bf 1}_N$$

In [12]:
np.matmul(RQ,RQ.transpose())+np.matmul(RP,RP.transpose())

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

$${\bf R}_\text{q}{\bf R}_\text{p}^\top-{\bf R}_\text{p}{\bf R}_\text{q}^\top = {\bf J}$$

In [13]:
np.matmul(RQ,RP.transpose())-np.matmul(RP,RQ.transpose())

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.]], dtype=float32)

$${\bf R}_\text{p}^\top {\bf R}_\text{q} = {\bf 0}_{n}$$

In [14]:
np.matmul(RP.transpose(), RQ)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

$${\bf R}_\text{q}^\top {\bf R}_\text{q} = {\bf 1}_{n}$$

In [15]:
np.matmul(RQ.transpose(), RQ)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

## Verify the symplectic matrix

In [16]:
M, MI, U = ps.RandomSymplectic(N)

In [17]:
tf.print(M)

array([[ 0.66057816,  0.35991848, -0.35705431,  0.13566934, -0.19077898,
        -0.3794487 ,  0.13754525,  0.14274799,  0.12160596,  0.23181805],
       [-0.35991848,  0.66057816, -0.13566934, -0.35705431,  0.3794487 ,
        -0.19077898, -0.14274799,  0.13754525, -0.23181805,  0.12160596],
       [-0.13970341,  0.54329839,  0.49634949,  0.48239991, -0.19139302,
         0.09754611,  0.1803355 ,  0.15863988,  0.18360226, -0.26209446],
       [-0.54329839, -0.13970341, -0.48239991,  0.49634949, -0.09754611,
        -0.19139302, -0.15863988,  0.1803355 ,  0.26209446,  0.18360226],
       [-0.0022795 , -0.12339634,  0.02187031,  0.42942148,  0.45976788,
        -0.08622355,  0.5489722 , -0.08439328, -0.48330277,  0.19746332],
       [ 0.12339634, -0.0022795 , -0.42942148,  0.02187031,  0.08622355,
         0.45976788,  0.08439328,  0.5489722 , -0.19746332, -0.48330277],
       [-0.16363392, -0.10168516,  0.15324967, -0.33453815, -0.20485988,
         0.18004413,  0.47454327,  0.48848456

In [18]:
utilities.printonscreennp(MI)

+0.7+0.0i -0.4+0.0i -0.1+0.0i -0.5+0.0i -0.0+0.0i +0.1+0.0i -0.2+0.0i +0.1+0.0i +0.3+0.0i -0.0+0.0i 
+0.4+0.0i +0.7+0.0i +0.5+0.0i -0.1+0.0i -0.1+0.0i -0.0+0.0i -0.1+0.0i -0.2+0.0i +0.0+0.0i +0.3+0.0i 
-0.4+0.0i -0.1+0.0i +0.5+0.0i -0.5+0.0i +0.0+0.0i -0.4+0.0i +0.2+0.0i +0.3+0.0i +0.1+0.0i -0.2+0.0i 
+0.1+0.0i -0.4+0.0i +0.5+0.0i +0.5+0.0i +0.4+0.0i +0.0+0.0i -0.3+0.0i +0.2+0.0i +0.2+0.0i +0.1+0.0i 
-0.2+0.0i +0.4+0.0i -0.2+0.0i -0.1+0.0i +0.5+0.0i +0.1+0.0i -0.2+0.0i -0.2+0.0i +0.6+0.0i -0.4+0.0i 
-0.4+0.0i -0.2+0.0i +0.1+0.0i -0.2+0.0i -0.1+0.0i +0.5+0.0i +0.2+0.0i -0.2+0.0i +0.4+0.0i +0.6+0.0i 
+0.1+0.0i -0.1+0.0i +0.2+0.0i -0.2+0.0i +0.5+0.0i +0.1+0.0i +0.5+0.0i -0.5+0.0i -0.3+0.0i -0.1+0.0i 
+0.1+0.0i +0.1+0.0i +0.2+0.0i +0.2+0.0i -0.1+0.0i +0.5+0.0i +0.5+0.0i +0.5+0.0i +0.1+0.0i -0.3+0.0i 
+0.1+0.0i -0.2+0.0i +0.2+0.0i +0.3+0.0i -0.5+0.0i -0.2+0.0i +0.2+0.0i -0.5+0.0i +0.4+0.0i -0.3+0.0i 
+0.2+0.0i +0.1+0.0i -0.3+0.0i +0.2+0.0i +0.2+0.0i -0.5+0.0i +0.5+0.0i +0.2+0.0i +0.3+0.0i +

In [19]:
M.shape

(10, 10)

In [20]:
MI.shape

(10, 10)

$${\bf M}{\bf M_I}={\bf 1}_N$$

In [21]:
utilities.printonscreennp(np.matmul(M,MI))

+1.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
-0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i 
-0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +

$${\bf M}{\bf J}{\bf M}^\top={\bf J}$$

In [22]:
utilities.printonscreennp(np.matmul(M, np.matmul(J,M.transpose()) ))

+0.0+0.0i +1.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i 
-1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i 
-0.0+0.0i -0.0+0.0i -0.0+0.0i +1.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i -1.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i 
-0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i -1.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -0.0+0.0i -1.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i 
-0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0+0.0i -1.0+0.0i -

## Verify the properties of the unitary matrix

In [23]:
utilities.printonscreennp(U)

+0.7-0.4i -0.4-0.1i -0.2+0.4i +0.1-0.1i +0.1-0.2i 
-0.1-0.5i +0.5-0.5i -0.2-0.1i +0.2-0.2i +0.2+0.3i 
-0.0+0.1i +0.0-0.4i +0.5+0.1i +0.5+0.1i -0.5-0.2i 
-0.2+0.1i +0.2+0.3i -0.2-0.2i +0.5-0.5i +0.2-0.5i 
+0.3-0.0i +0.1-0.2i +0.6-0.4i -0.3-0.1i +0.4-0.3i 


$${\bf U}^\dagger = ({\bf U}^\top)^*$$

In [24]:
Udagger =U.transpose().conjugate(); utilities.printonscreennp(Udagger)

+0.7+0.4i -0.1+0.5i -0.0-0.1i -0.2-0.1i +0.3+0.0i 
-0.4+0.1i +0.5+0.5i +0.0+0.4i +0.2-0.3i +0.1+0.2i 
-0.2-0.4i -0.2+0.1i +0.5-0.1i -0.2+0.2i +0.6+0.4i 
+0.1+0.1i +0.2+0.2i +0.5-0.1i +0.5+0.5i -0.3+0.1i 
+0.1+0.2i +0.2-0.3i -0.5+0.2i +0.2+0.5i +0.4+0.3i 


$${\bf U}^\dagger {\bf U}={\bf 1}_{n}$$

In [25]:
utilities.printonscreennp(np.matmul(Udagger,U))

+1.0+0.0i -0.0-0.0i +0.0+0.0i +0.0+0.0i +0.0-0.0i 
-0.0+0.0i +1.0+0.0i +0.0-0.0i -0.0+0.0i +0.0-0.0i 
+0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0-0.0i -0.0-0.0i 
+0.0-0.0i -0.0-0.0i +0.0+0.0i +1.0+0.0i -0.0+0.0i 
+0.0+0.0i +0.0+0.0i -0.0+0.0i -0.0-0.0i +1.0+0.0i 


$${\bf U}_R=\Re{\bf U}$$

In [26]:
UR = np.real(U); utilities.printonscreennp(UR)

+0.7+0.0i -0.4+0.0i -0.2+0.0i +0.1+0.0i +0.1+0.0i 
-0.1+0.0i +0.5+0.0i -0.2+0.0i +0.2+0.0i +0.2+0.0i 
-0.0+0.0i +0.0+0.0i +0.5+0.0i +0.5+0.0i -0.5+0.0i 
-0.2+0.0i +0.2+0.0i -0.2+0.0i +0.5+0.0i +0.2+0.0i 
+0.3+0.0i +0.1+0.0i +0.6+0.0i -0.3+0.0i +0.4+0.0i 


$${\bf U}_I=\Im {\bf U}$$

In [27]:
UI = np.imag(U); utilities.printonscreennp(UI)

-0.4+0.0i -0.1+0.0i +0.4+0.0i -0.1+0.0i -0.2+0.0i 
-0.5+0.0i -0.5+0.0i -0.1+0.0i -0.2+0.0i +0.3+0.0i 
+0.1+0.0i -0.4+0.0i +0.1+0.0i +0.1+0.0i -0.2+0.0i 
+0.1+0.0i +0.3+0.0i -0.2+0.0i -0.5+0.0i -0.5+0.0i 
-0.0+0.0i -0.2+0.0i -0.4+0.0i -0.1+0.0i -0.3+0.0i 


$${\bf U}_R {\bf U}_R^\top+{\bf U}_I{\bf U}_I^\top={\bf 1}_{n}$$

In [28]:
utilities.printonscreennp(np.matmul(UR,UR.transpose())+np.matmul(UI,UI.transpose()))

+1.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
-0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +1.0+0.0i 


$${\bf U}_R {\bf U}_I^\top-{\bf U}_I{\bf U}_R^\top={\bf 0}_{n}$$

In [29]:
utilities.printonscreennp(np.matmul(UR,UI.transpose())-np.matmul(UI,UR.transpose()))

+0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i -0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i 
-0.0+0.0i -0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i 
