# Test the GaussianLayer class


<img src="../img/logo_circular.png" width="20" height="20" />@by claudio<br>

nonlinearxwaves@gmail.com<br>
@created 7 nov 2021<br>
@version 15 may 2023

In [1]:
import numpy as np
from thqml import phasespace as ps
from thqml.utilities import utilities
import tensorflow as tf
import tensorflow.keras as tfk

2023-05-14 11:22:04.651193: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-14 11:22:04.651217: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


## Dimension

In [2]:
N=20

## Create a covariance matrix and a displacement vector

In [3]:
g=np.eye(N) # identity matrix
d=np.ones((N,1)) # displacement vector

## Create a Gaussian Layer with an identity matrix as g and identity displacement vector

In [4]:
G=ps.GaussianLayer(g,d)

2023-05-14 11:22:07.070355: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-05-14 11:22:07.070382: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2023-05-14 11:22:07.070407: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (x1): /proc/driver/nvidia/version does not exist
2023-05-14 11:22:07.070732: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Create a data

In [5]:
Nbatch=5

In [6]:
xdata=np.random.rand(Nbatch,N)

In [7]:
chir, chii =G(xdata)

In [8]:
print(chir, chii)

tf.Tensor(
[[-0.17403965]
 [-0.1911797 ]
 [ 0.06649071]
 [ 0.09819441]
 [-0.17848293]], shape=(5, 1), dtype=float32) tf.Tensor(
[[ 0.20885466]
 [ 0.06339978]
 [-0.08818472]
 [-0.02622793]
 [-0.07659712]], shape=(5, 1), dtype=float32)


In [9]:
print(chii)

tf.Tensor(
[[ 0.20885466]
 [ 0.06339978]
 [-0.08818472]
 [-0.02622793]
 [-0.07659712]], shape=(5, 1), dtype=float32)


## Test the vacuum layer

### create the layer

In [10]:
vacuum=ps.VacuumLayer(N)
chir_vacuum, chii_vacuum=vacuum(xdata)
print(chir_vacuum, chii_vacuum)

tf.Tensor(
[[0.27186406]
 [0.20141798]
 [0.11044256]
 [0.10163683]
 [0.1942248 ]], shape=(5, 1), dtype=float32) tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(5, 1), dtype=float32)


In [11]:
chir_vacuum, chir_vacuum=vacuum(xdata)

In [12]:
print(chir)

tf.Tensor(
[[-0.17403965]
 [-0.1911797 ]
 [ 0.06649071]
 [ 0.09819441]
 [-0.17848293]], shape=(5, 1), dtype=float32)


## Create a model with two layers

In [13]:
N=20
vacuum=ps.VacuumLayer(N)
x=tfk.layers.Input(N)
chir, chii = vacuum(x)
vacuum_model=tfk.Model(inputs=x, outputs=[chir,chii])
print(vacuum_model(xdata))

[<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.27186406],
       [0.20141798],
       [0.11044256],
       [0.10163683],
       [0.1942248 ]], dtype=float32)>, <tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>]
