# Test the GaussianLayer class


<img src="../img/logo_circular.png" width="20" height="20" />@by claudio<br>

nonlinearxwaves@gmail.com<br>
@created 7 nov 2021<br>
@version 23 sep 2023

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # disable warning messages

In [2]:
import numpy as np
from thqml import phasespace as ps
from thqml.utilities import utilities
import tensorflow as tf
import tensorflow.keras as tfk

## Dimension

In [3]:
N=20

## Create a covariance matrix and a displacement vector

In [4]:
g=np.eye(N) # identity matrix
d=np.ones((N,1)) # displacement vector

## Create a Gaussian Layer with an identity matrix as g and identity displacement vector

In [5]:
G=ps.GaussianLayer(g,d)

## Create a data

In [6]:
Nbatch=5

In [7]:
xdata=np.random.rand(Nbatch,N)

In [8]:
chir, chii =G(xdata)

In [9]:
print(chir, chii)

tf.Tensor(
[[-0.02112762]
 [-0.19748256]
 [-0.09532962]
 [ 0.00917837]
 [-0.22657184]], shape=(5, 1), dtype=float32) tf.Tensor(
[[-0.13866772]
 [-0.11626254]
 [-0.16041031]
 [ 0.0601069 ]
 [ 0.02437205]], shape=(5, 1), dtype=float32)


In [10]:
print(chii)

tf.Tensor(
[[-0.13866772]
 [-0.11626254]
 [-0.16041031]
 [ 0.0601069 ]
 [ 0.02437205]], shape=(5, 1), dtype=float32)


## Test the vacuum layer

### create the layer

In [11]:
vacuum=ps.VacuumLayer(N)
chir_vacuum, chii_vacuum=vacuum(xdata)
print(chir_vacuum, chii_vacuum)

tf.Tensor(
[[0.140268  ]
 [0.22916444]
 [0.18659905]
 [0.06080363]
 [0.22787891]], shape=(5, 1), dtype=float32) tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(5, 1), dtype=float32)


In [12]:
chir_vacuum, chir_vacuum=vacuum(xdata)

In [13]:
print(chir)

tf.Tensor(
[[-0.02112762]
 [-0.19748256]
 [-0.09532962]
 [ 0.00917837]
 [-0.22657184]], shape=(5, 1), dtype=float32)


## Create a model with two layers

In [14]:
N=20
vacuum=ps.VacuumLayer(N)
x=tfk.layers.Input(N)
chir, chii = vacuum(x)
vacuum_model=tfk.Model(inputs=x, outputs=[chir,chii])
print(vacuum_model(xdata))

[<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.140268  ],
       [0.22916444],
       [0.18659905],
       [0.06080363],
       [0.22787891]], dtype=float32)>, <tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>]
