# Two-mode squeezed state model

Use the multi-head (2-head) gates in the phase space 
to create a network that represent a two mode squeezed vacuum
by starting from a Gaussian state and making a pullback

The state propagate in a complex medium

<img src="../img/logo_circular.png" width="20" height="20" />@by claudio<br>


nonlinearxwaves@gmail.com<br>
@created 10 december 2020
@version 5 december 2021

In [2]:
import numpy as np
from quomplex2021 import phasespace as ps
from quomplex2021.utilities import utilities
import tensorflow as tf
#import tensorflow_addons as tfa
from tensorflow import keras
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping

2021-12-05 15:55:31.288618: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-05 15:55:31.288643: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [3]:
tf_complex = tf.complex
tf_real = tf.float32
np_complex = complex
np_real = np.float64

In [4]:
tf.keras.backend.clear_session()

In [5]:
np.set_printoptions(precision=2)

## Dimension (number of modes times 2)

In [6]:
N = 8

## Index of the squeezed mode 1 (between 0 an N/2)

In [7]:
n_s1=1

## Index of the squeezed mode 2 

In [8]:
n_s2=3

## Displacer

In [9]:
dtarget=3.2*np.ones((N,1))
norm = np.linalg.norm(dtarget)
dtarget = dtarget /norm
displacer = ps.DisplacementLayerConstant(dtarget)

2021-12-05 15:55:34.423826: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-05 15:55:34.423854: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-05 15:55:34.423878: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (x1): /proc/driver/nvidia/version does not exist
2021-12-05 15:55:34.424151: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Build vacuum by the Gaussian state

In [10]:
vacuum = ps.VacuumLayer(N)

## Two mode squeezer

In [11]:
r_np=1.0;
theta_np=np.pi/7;

In [12]:
squeezer2m=ps.TwoModeSqueezerLayer(N, r_np=r_np, theta_np=theta_np, n_s1=n_s1, n_s2=n_s2)

In [13]:
Ms, MsI=squeezer2m.get_M(); Ms_np = Ms.numpy();print(Ms_np)

[[ 1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    1.54  0.    0.    0.   -1.06 -0.51]
 [ 0.    0.    0.    1.54  0.    0.   -0.51  1.06]
 [ 0.    0.    0.    0.    1.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    1.    0.    0.  ]
 [ 0.    0.   -1.06 -0.51  0.    0.    1.54  0.  ]
 [ 0.    0.   -0.51  1.06  0.    0.    0.    1.54]]


### Check if the matrix is symplectic

In [14]:
utilities.printonscreennp(np.matmul(Ms.numpy(),MsI.numpy()))

+1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i +0.0+0.0i 
+0.0+0.0i +0.0+0.0i +0.0+0.0i -0.0+0.0i +0.0+0.0i +0.0+0.0i +0.0+0.0i +1.0+0.0i 


The previous matrix must be unitary

# Build the model

In [15]:
xin = tf.keras.layers.Input(N)
x1, d1 = squeezer2m(xin)
chir, chii = vacuum(x1, d1)
squeezed2m = tf.keras.Model(inputs = xin, outputs=[chir, chii])

# Evaluate the covariance matrix

In [17]:
cov_layer = ps.CovarianceLayer(N)
covariance_matrix, mean_R,_ = cov_layer(chir,chii, squeezed2m)
squeezed2m_cov = tf.keras.Model(inputs = xin, outputs=[covariance_matrix, mean_R])

# Training points

In [18]:
xtrain = np.random.rand(1, N)-0.5

# Covariance and displacement

In [19]:
cov0,d0=squeezed2m_cov(xtrain); 

## Displacement

In [20]:
print(d0)

tf.Tensor([[0. 0. 0. 0. 0. 0. 0. 0.]], shape=(1, 8), dtype=float32)


## Eigenvalues and eigenvectors of the covariance matrix

In [21]:
np.linalg.eig(cov0.numpy())

(array([7.39, 0.14, 0.14, 7.39, 1.  , 1.  , 1.  , 1.  ], dtype=float32),
 array([[ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ],
        [-0.64, -0.64,  0.53,  0.23,  0.  ,  0.  ,  0.  ,  0.  ],
        [-0.31, -0.31,  0.47, -0.67,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ],
        [ 0.71, -0.71,  0.68,  0.08,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  , -0.2 , -0.7 ,  0.  ,  0.  ,  0.  ,  0.  ]],
       dtype=float32))

Note that the squeezed eigenvectors (with not unitary eigenvalues) spans the space of modes n_s1 and n_s2